@BankApi_HostAddress = http://localhost:5240

@token = YOUR_TOKEN_HERE


### Kullanıcı Kayıt Testi

POST {{BankApi_HostAddress}}/api/Auth/register
Content-Type: application/json

{
  "firstName": "Beyza",
  "lastName": "Ulukuş",
  "email": "beyza@test.com",
  "password": "Password123!",
  "tckn": "12345678901",
  "phoneNumber": "05551112233",
  "dateOfBirth": "2006-12-13T00:00:00.000Z"
}


### Kullanıcı Giriş Testi

POST {{BankApi_HostAddress}}/api/Auth/login
Content-Type: application/json

{
  "email": "beyza@gmail.com",
  "password": "1111"
}


### Token OLMADAN Korumalı Endpoint

GET {{BankApi_HostAddress}}/api/Test/protected


### Token İLE Korumalı Endpoint

GET {{BankApi_HostAddress}}/api/Test/protected
Authorization: Bearer {{token}}


### Yeni Banka Hesabı Açma

POST {{BankApi_HostAddress}}/api/Account/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "currencyId": 2
}


### Kullanıcının Hesaplarını Listele

GET {{BankApi_HostAddress}}/api/Account/my-accounts
Authorization: Bearer {{token}}


### Para Transferi

POST {{BankApi_HostAddress}}/api/Transaction/transfer
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "sourceAccountId": 1,
  "targetIban": "TR990006201208772620015768",
  "amount": 250,
  "description": "test transferi"
}


### İşlem Geçmişi

GET {{BankApi_HostAddress}}/api/Transaction/history
Authorization: Bearer {{token}}


### Para Yatırma

POST {{BankApi_HostAddress}}/api/Transaction/deposit
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "accountId": 1,
  "amount": 1000,
  "description": "ATM Para Yatırma Testi"
}


### Para Çekme

POST {{BankApi_HostAddress}}/api/Transaction/withdraw
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "accountId": 1,
  "amount": 250,
  "description": "ATM Para Çekme Testi"
}


### THYAO TEST

GET {{BankApi_HostAddress}}/api/Investment/stock/THYAO
Authorization: Bearer {{token}}


### BIST 100 TEST

GET {{BankApi_HostAddress}}/api/Investment/index/XU100
Authorization: Bearer {{token}}


### THYAO HISTORY

GET {{BankApi_HostAddress}}/api/Investment/history/THYAO?period=1mo&interval=1d
Authorization: Bearer {{token}}


### Investment Account

GET {{BankApi_HostAddress}}/api/Investment/account
Authorization: Bearer {{token}}


### Yatırım Hesabına Para Aktar

POST {{BankApi_HostAddress}}/api/Investment/deposit
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "sourceAccountId": 2,
  "amount": 1000
}


### BUY THYAO

POST {{BankApi_HostAddress}}/api/Investment/buy
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "symbol": "THYAO",
  "quantity": 1
}


### Portfolio

GET {{BankApi_HostAddress}}/api/Investment/portfolio
Authorization: Bearer {{token}}


### SELL GARAN

POST {{BankApi_HostAddress}}/api/Investment/sell
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "symbol": "GARAN",
  "quantity": 1
}


### Investment Transactions

GET {{BankApi_HostAddress}}/api/Investment/transactions
Authorization: Bearer {{token}}