
@BankApi_HostAddress = http://localhost:5240

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJiZXl6YUBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJDdXN0b21lciIsImV4cCI6MTc4NjcwODM2NSwiaXNzIjoiQmFua0FwaSIsImF1ZCI6IkJhbmtVSSJ9.w6eljKLivkK078wzZlcgJzE3oK28fTH4oihbNi_cFkU

POST {{BankApi_HostAddress}}/api/Auth/register
Content-Type: application/json

{
  "firstName": "Beyza",
  "lastName": "Ulukuş",
  "email": "beyza@test.com",
  "password": "Password123!",
  "tckn": "12345678901",
  "phoneNumber": "05551112233",
  "dateOfBirth": "2006-12-13T00:00:00.000Z"
}
### Kullanıcı Giriş Testi (Başarılı Senaryo)
POST {{BankApi_HostAddress}}/api/Auth/login
Content-Type: application/json

{
  "email": "beyza@gmail.com",
  "password": "1111"
}
### 1. Token OLMADAN Korumalı Kapıyı Çalma (401 Red Almalıyız)
GET http://localhost:5240/api/Test/protected

###

### 2. Token İLE Korumalı Kapıyı Çalma (200 OK Almalıyız)
# NOT: Buradaki {{YOUR_TOKEN}} yerine Login olduğunda sana dönen o uzun eyJ... metnini yapıştır!
GET http://localhost:5240/api/Test/protected
Authorization: Bearer {{token}}

### 3. Yeni Banka Hesabı Açma (TL Hesabı -> CurrencyId: 1)
POST http://localhost:5240/api/Account/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "currencyId": 2
}
### Kullanıcının Hesaplarını Listele
GET http://localhost:5240/api/account/my-accounts
Authorization: Bearer {{token}}

### Para Transferi

POST http://localhost:5240/api/transaction/transfer
Authorization: Bearer {{token}}

Content-Type: application/json

{
  "sourceAccountId": 1,
  "targetIban": "TR990006201208772620015768",
  "amount": 250,
  "description": "test transferi"
}

### 4. İşlem Geçmişi (Ekstre / History)
GET http://localhost:5240/api/Transaction/history
Authorization: Bearer {{token}}

{
  "userId": 1
}

### Para Yatırma
POST http://localhost:5240/api/Transaction/deposit
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "accountId": 1,
  "amount": 1000,
  "description": "ATM Para Yatırma Testi"
}

### Para Çekme
POST http://localhost:5240/api/Transaction/withdraw
Content-Type: application/json
Authorization: Bearer  {{token}}

{
  "accountId": 1,
  "amount": 250,
  "description": "ATM Para Çekme Testi"
}

### THYAO TEST

GET http://localhost:5240/api/Investment/stock/THYAO
Authorization: Bearer {{token}}


### BIST 100 TEST

GET http://localhost:5240/api/Investment/index/XU100
Authorization: Bearer {{token}}
### THYAO HISTORY

GET http://localhost:5240/api/Investment/history/THYAO?period=1mo&interval=1d
Authorization: Bearer {{token}}

### Investment Account

GET http://localhost:5240/api/Investment/account
Authorization: Bearer {{token}}

### Yatırım hesabına para aktar

POST http://localhost:5240/api/Investment/deposit
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "sourceAccountId": 2,
  "amount": 1000
}
### BUY THYAO

POST http://localhost:5240/api/Investment/buy
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "symbol": "THYAO",
  "quantity": 1
}

### Portfolio

GET http://localhost:5240/api/Investment/portfolio
Authorization: Bearer {{token}}